from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class PermissionLevel(str, Enum):
    """Security clearance level required to execute a given Tool."""
    SAFE = "SAFE"
    CONFIRM = "CONFIRM"
    ADMIN = "ADMIN"


class ToolMetadata(BaseModel):
    """Unified structure representing tool registrations in JARVIS."""
    name: str = Field(..., description="Unique system-wide identifier name of the tool.")
    description: str = Field(..., description="Detailed description of what the tool does and its parameters.")
    input_schema: Dict[str, Any] = Field(..., description="JSON Schema (draft-07 or similar) of the tool's inputs.")
    output_schema: Dict[str, Any] = Field(..., description="JSON Schema of the tool's expected outputs.")
    permission_level: PermissionLevel = Field(
        default=PermissionLevel.SAFE, 
        description="The minimum security authorization tier required."
    )


class StepStatus(str, Enum):
    """Execution status of a discrete plan step."""
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskStep(BaseModel):
    """A single sub-task or action block within a larger execution plan."""
    step_id: int = Field(..., description="Sequential index representing step order.")
    description: str = Field(..., description="Natural language description of what this step accomplishes.")
    tool_name: Optional[str] = Field(None, description="The name of the tool allocated to this step.")
    tool_input: Optional[Dict[str, Any]] = Field(None, description="Dynamic argument payload passed to the tool.")
    status: StepStatus = Field(default=StepStatus.PENDING, description="Execution status.")
    result: Optional[str] = Field(None, description="String representation of tool success output.")
    error: Optional[str] = Field(None, description="Stack trace or message text if tool execution failed.")


class PlanStatus(str, Enum):
    """Overall status of an execution plan."""
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskPlan(BaseModel):
    """The full list of decomposed steps generated by the Planner to satisfy a prompt."""
    task_id: str = Field(..., description="Unique UUID referencing this specific execution plan.")
    prompt: str = Field(..., description="The user's original request prompt.")
    steps: List[TaskStep] = Field(default_factory=list, description="Ordered list of execution steps.")
    status: PlanStatus = Field(default=PlanStatus.PENDING, description="Overall execution status.")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), 
        description="Time plan was initialized."
    )
    completed_at: Optional[datetime] = Field(None, description="Time when final step resolved or plan aborted.")


class MessageRole(str, Enum):
    """Role classification for conversation history."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    PLANNER = "planner"


class AgentMessage(BaseModel):
    """A structured message exchange between a user, coordinator, or dynamic agent."""
    role: MessageRole = Field(..., description="Who generated the message.")
    content: str = Field(..., description="Message string content.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), 
        description="Time message was recorded."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Optional auxiliary data (e.g. system state, vision token counts, etc.)."
    )


class PluginInfo(BaseModel):
    """Descriptor model used to validate self-registering plugins."""
    name: str = Field(..., description="Directory name or identity of the plugin.")
    description: str = Field(..., description="Short explanation of what capability this plugin adds.")
    version: str = Field(..., description="Semantic version of the plugin.")
    author: Optional[str] = Field(None, description="Developer details.")
    enabled: bool = Field(default=True, description="Whether this plugin should be loaded at runtime.")
